name: duckdb
base: core24
version: '1.0.0-1'
license: MIT
summary: DuckDB CLI
description: |
  DuckDB is a fast in-process analytical database.
  Please see https://duckdb.org for information about DuckDB.

  This snap contains the DuckDB CLI with some core extensions included:
    autocomplete
    fts
    icu
    httpfs
    json
    inet

grade: devel
confinement: strict

apps:
  duckdb:
    command: usr/local/bin/duckdb

parts:
  duckdb:
    source: https://github.com/duckdb/duckdb/archive/refs/tags/v1.0.0.tar.gz
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_EXTENSIONS='autocomplete;icu;fts;httpfs;json;inet'
    build-packages:
      - git
      - libssl-dev
