name: duckdb
base: core24
version: '1.0.0-1'
license: MIT
summary: DuckDB CLI
description: |
  DuckDB is a fast in-process analytical database.
  This snap contains the DuckDB CLI and some core extensions.
  Please see https://duckdb.org for information about DuckDB.
    and https://github.com/lab1702/duckdb-snap for
    information about this snap.

grade: devel
confinement: strict

apps:
  duckdb:
    command: usr/local/bin/duckdb

parts:
  duckdb:
    source: https://github.com/duckdb/duckdb/archive/refs/tags/v1.0.0.tar.gz
    plugin: cmake
    cmake-parameters:
      - -DBUILD_EXTENSIONS='autocomplete;fts;httpfs;icu;inet;json'
    build-packages:
      - git
      - libssl-dev
